package io.floci.gcp.services.gke.operations;

public enum OperationType {
    CREATE_CLUSTER,
    DELETE_CLUSTER,
    UPDATE_CLUSTER,
    CREATE_NODE_POOL,
    DELETE_NODE_POOL,
    UPDATE_NODE_POOL,
    SET_LABELS,
    SET_MASTER_AUTH,
    SET_NETWORK_POLICY,
    SET_ADDONS_CONFIG,
    SET_LOGGING_SERVICE,
    SET_MONITORING_SERVICE,
    SET_LOCATIONS,
    SET_NODE_POOL_AUTOSCALING,
    SET_NODE_POOL_MANAGEMENT,
    SET_NODE_POOL_SIZE,
    SET_LEGACY_ABAC,
    SET_MAINTENANCE_POLICY,
    START_IP_ROTATION,
    COMPLETE_IP_ROTATION,
    COMPLETE_NODE_POOL_UPGRADE,
    ROLLBACK_NODE_POOL_UPGRADE
}
