package io.floci.gcp.core.tls;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.quarkus.runtime.annotations.RegisterForReflection;

import java.util.List;
import java.util.Objects;

/**
 * Metadata for self-signed TLS certificates generated by floci-gcp.
 *
 * <p>This metadata is persisted alongside certificate files to track which hostnames
 * were used during generation. It enables detection of configuration changes on
 * restart, allowing the system to regenerate certificates when hostname configuration
 * changes.
 *
 * <p>The metadata file is stored as JSON at
 * {@code {persistent-path}/tls/floci-gcp-selfsigned.metadata.json}.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@RegisterForReflection
public class CertificateMetadata {

    /**
     * List of hostnames that were included in the certificate's Subject Alternative Names (SANs).
     * This includes both default hostnames (localhost, 127.0.0.1, etc.) and custom hostnames
     * from FLOCI_GCP_HOSTNAME and FLOCI_GCP_BASE_URL configuration.
     */
    private List<String> hostnames;

    /**
     * floci-gcp version that generated the certificate.
     * Used for debugging and potential future migration scenarios.
     */
    private String version;

    public CertificateMetadata() {
    }

    public CertificateMetadata(List<String> hostnames, String version) {
        this.hostnames = hostnames;
        this.version = version;
    }

    public List<String> getHostnames() {
        return hostnames;
    }

    public void setHostnames(List<String> hostnames) {
        this.hostnames = hostnames;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CertificateMetadata that = (CertificateMetadata) o;
        return Objects.equals(hostnames, that.hostnames)
                && Objects.equals(version, that.version);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hostnames, version);
    }

    @Override
    public String toString() {
        return "CertificateMetadata{"
                + "hostnames=" + hostnames
                + ", version='" + version + '\''
                + '}';
    }
}
